-- Create the trips table
create table public.trips (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  trip_name text,
  parsed_data jsonb not null
);

-- Enable Row Level Security (RLS)
alter table public.trips enable row level security;

-- Create a policy that allows anyone to read/write for this prototype
-- (In a real app, you would restrict this to authenticated users)
create policy "Enable read access for all users" on public.trips for select using (true);
create policy "Enable insert access for all users" on public.trips for insert with check (true);
